name: message_repository

version: 1.0.0+1

environment:
  sdk: ">=2.6.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.23.1
  equatable: ^1.1.1
  firebase_core: ^0.4.4+3
  cloud_firestore: ^0.13.4+2
